In [1]:
import pandas as pd
import numpy as np
import json
from sklearn.linear_model import LinearRegression

In [2]:
# 1. Load the dataset
data = pd.read_csv("First Draft dataset.csv")

C:\Users\USER\AppData\Local\Temp\ipykernel_12404\175281652.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("First Draft dataset.csv")

In [3]:
data.head()

,__indexer_id,__confirmed,__block_number,block_number,log_index,transaction_hash,timestamp,exchange_name,contract_version,aggregator_name,...,description,image_url,external_url,media_url,properties,metadata_url,last_refreshed,flattened_properties,__updated_block_number,collection_name
0,opensea-seaport-nft-sales-v2,True,16889880,16889880,293,0x5f438f5b5dd1ae8ab284bfec04afa582d8f15f60cadb...,2023-03-23T11:15:23Z,opensea,seaport,NaN,...,NaN,https://ipfs.io/ipfs/QmWCjnE1DKmFV9t2ubnABPYC9...,NaN,NaN,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",https://boredapeyachtclub.com/api/mutants/10972,2023-02-02T09:05:53Z,"{""Fur"":""M1 Dark Brown"",""Hat"":""M1 Fisherman's H...",16147201,MutantApeYachtClub
1,blur-nft-sales,True,16889821,16889821,390,0x92af5b4a0c845c9d70870cdf78090ff3b2c78fd5d01f...,2023-03-23T11:03:35Z,blur,v1,NaN,...,NaN,https://ipfs.io/ipfs/QmXAdmV46nFRJqQNxnPbFVzU4...,NaN,NaN,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",https://boredapeyachtclub.com/api/mutants/12974,2023-02-02T11:07:30Z,"{""Fur"":""M1 Brown"",""Hat"":""M1 Stuntman Helmet"",""...",16144177,MutantApeYachtClub
2,blur-nft-sales,True,16889821,16889821,395,0x92af5b4a0c845c9d70870cdf78090ff3b2c78fd5d01f...,2023-03-23T11:03:35Z,blur,v1,NaN,...,NaN,https://ipfs.io/ipfs/QmYvL9V9Awf4RC56q4cKMKBhe...,NaN,NaN,"[{""trait_type"":""Background"",""value"":""M1 Army G...",https://boredapeyachtclub.com/api/mutants/15768,2023-02-06T05:36:13Z,"{""Fur"":""M1 Pink"",""Eyes"":""M1 Bloodshot"",""Mouth""...",16145941,MutantApeYachtClub
3,blur-nft-sales,True,16889821,16889821,400,0x92af5b4a0c845c9d70870cdf78090ff3b2c78fd5d01f...,2023-03-23T11:03:35Z,blur,v1,NaN,...,NaN,https://ipfs.io/ipfs/QmXXH34kumGDiVTtiPon2jc56...,NaN,NaN,"[{""trait_type"":""Background"",""value"":""M1 Purple...",https://boredapeyachtclub.com/api/mutants/434,2023-02-06T12:17:00Z,"{""Fur"":""M1 Pink"",""Hat"":""M1 Beanie"",""Eyes"":""M1 ...",16140674,MutantApeYachtClub
4,blur-nft-sales,True,16889814,16889814,176,0xe3b8635734173b111cdf539563694816a534887fd5d6...,2023-03-23T11:02:11Z,blur,v1,NaN,...,NaN,https://ipfs.io/ipfs/QmVqefVyfjPN3BCh1VKEVo16D...,NaN,NaN,"[{""trait_type"":""Background"",""value"":""M1 New Pu...",https://boredapeyachtclub.com/api/mutants/5412,2023-02-02T19:34:14Z,"{""Fur"":""M1 Dark Brown"",""Hat"":""M1 Cowboy Hat"",""...",16140674,MutantApeYachtClub

In [4]:
# 2. Drop unnecessary columns
drop_cols = ['__indexer_id', '__confirmed', '__block_number', 'block_number', 'log_index', 'transaction_hash', 
             'exchange_name', 'contract_version', 'aggregator_name', 'contract_address', 'is_multi_token_sale',
             'multi_token_sale_index', 'price', 'native_price', 'payment_token_address', 'quantity', 'seller_address', 
             'buyer_address', 'supply', 'name', 'description', 'image_url', 'external_url', 'media_url', 'metadata_url', 
             'last_refreshed', 'flattened_properties', '__updated_block_number']
data = data.drop(columns=drop_cols, errors='ignore')

In [5]:
data.head(50)

,timestamp,token_id,usd_price,eth_price,royalty_fee,platform_fee,minted_timestamp,properties,collection_name
0,2023-03-23T11:15:23Z,10972,21696.37,12.3650,0.061825,0.0,2022-04-24T10:16:44Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub
1,2023-03-23T11:03:35Z,12974,21129.12,12.0600,0.060300,0.0,2022-01-17T15:36:12Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
2,2023-03-23T11:03:35Z,15768,21111.60,12.0500,0.060250,0.0,2022-03-16T23:38:59Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
3,2023-03-23T11:03:35Z,434,21024.00,12.0000,0.060000,0.0,2021-08-29T00:49:00Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
4,2023-03-23T11:02:11Z,5412,21568.22,12.2800,0.061400,0.0,2021-08-29T01:19:51Z,"[{""trait_type"":""Background"",""value"":""M1 New Pu...",MutantApeYachtClub
5,2023-03-23T10:57:47Z,7877,21606.55,12.3000,0.061500,0.0,2021-08-29T01:27:24Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub
6,2023-03-23T10:57:11Z,2994,21606.55,12.3000,0.061500,0.0,2021-08-29T01:10:23Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
7,2023-03-23T10:57:11Z,15294,21641.68,12.3200,0.061600,0.0,2021-09-11T16:46:55Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
8,2023-03-23T10:52:59Z,1074,21674.78,12.3300,0.061650,0.0,2021-08-29T00:55:14Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub
9,2023-03-23T10:51:11Z,7554,21681.32,12.3300,0.061650,0.0,2021-08-29T01:25:59Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub
10,2023-03-23T10:51:11Z,8928,21681.32,12.3300,0.061650,0.0,2021-08-29T01:29:26Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
11,2023-03-23T10:51:11Z,23602,21681.32,12.3300,0.061650,0.0,2021-08-29T02:25:08Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
12,2023-03-23T10:48:35Z,9821,21679.47,12.3300,0.061650,0.0,2021-08-29T01:32:30Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
13,2023-03-23T10:48:35Z,9071,21679.47,12.3300,0.061650,0.0,2021-08-29T01:29:36Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
14,2023-03-23T10:48:35Z,12668,21697.05,12.3400,0.061700,0.0,2021-08-29T19:57:18Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub
15,2023-03-23T10:48:35Z,13510,21697.05,12.3400,0.061700,0.0,2021-08-29T06:21:28Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
16,2023-03-23T10:48:35Z,4885,21697.05,12.3400,0.061700,0.0,2021-08-29T01:17:53Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
17,2023-03-23T10:48:35Z,3951,21697.05,12.3400,0.061700,0.0,2021-08-29T01:14:10Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
18,2023-03-23T10:45:35Z,6236,21718.71,12.3500,0.061750,0.0,2021-08-29T01:22:26Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
19,2023-03-23T10:37:23Z,5122,21715.00,12.3500,0.061750,0.0,2021-08-29T01:19:04Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
20,2023-03-23T10:35:23Z,9729,21739.46,12.3500,0.061750,0.0,2021-08-29T01:32:16Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
21,2023-03-23T10:33:35Z,7735,21668.08,12.3500,0.061750,0.0,2021-08-29T01:26:49Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
22,2023-03-23T10:32:59Z,29922,21727.97,12.3500,0.061750,0.0,2021-08-29T10:24:18Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub
23,2023-03-23T10:32:35Z,25922,21727.97,12.3500,0.061750,0.0,2021-08-29T09:42:03Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub
24,2023-03-23T10:31:59Z,17138,21723.90,12.3500,0.061750,0.0,2021-08-29T02:22:30Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
25,2023-03-23T10:30:47Z,7244,27786.20,15.8000,0.079000,0.0,2021-08-29T01:25:33Z,"[{""trait_type"":""Background"",""value"":""M2 Purple...",MutantApeYachtClub
26,2023-03-23T10:08:35Z,10735,30820.30,17.5000,0.000000,0.0,2021-09-19T01:27:25Z,"[{""trait_type"":""Background"",""value"":""M2 Aquama...",MutantApeYachtClub
27,2023-03-23T08:48:11Z,9920,21706.73,12.3500,0.061750,0.0,2021-08-29T01:32:50Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
28,2023-03-23T08:48:11Z,12974,21706.73,12.3500,0.061750,0.0,2022-01-17T15:36:12Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
29,2023-03-23T08:44:11Z,1074,21701.91,12.3500,0.061750,0.0,2021-08-29T00:55:14Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub
30,2023-03-23T08:23:47Z,5122,21704.16,12.3600,0.061800,0.0,2021-08-29T01:19:04Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
31,2023-03-23T08:18:47Z,6236,21441.64,12.2121,0.305302,0.0,2021-08-29T01:22:26Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
32,2023-03-23T07:37:59Z,1074,21640.78,12.3400,0.061700,0.0,2021-08-29T00:55:14Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub
33,2023-03-23T07:37:59Z,8372,21640.78,12.3400,0.061700,0.0,2021-08-29T01:28:04Z,"[{""trait_type"":""Background"",""value"":""M1 New Pu...",MutantApeYachtClub
34,2023-03-23T07:36:35Z,23602,21648.81,12.3500,0.061750,0.0,2021-08-29T02:25:08Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
35,2023-03-23T07:36:35Z,9729,21648.81,12.3500,0.061750,0.0,2021-08-29T01:32:16Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
36,2023-03-23T07:24:35Z,13480,22596.54,12.9000,0.000000,0.0,2021-08-29T02:31:25Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
37,2023-03-23T06:40:59Z,15768,21673.36,12.3400,0.061700,0.0,2022-03-16T23:38:59Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
38,2023-03-23T06:36:23Z,434,21622.15,12.3400,0.061700,0.0,2021-08-29T00:49:00Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
39,2023-03-23T06:00:23Z,4190,21660.65,12.3400,0.061700,0.0,2021-08-29T01:14:48Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
40,2023-03-23T05:50:23Z,5122,21605.24,12.3400,0.061700,0.0,2021-08-29T01:19:04Z,"[{""trait_type"":""Background"",""value"":""M1 Purple...",MutantApeYachtClub
41,2023-03-23T04:06:35Z,172,21642.34,12.4190,0.062095,0.0,2021-08-29T00:46:19Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
42,2023-03-23T04:02:47Z,9920,21490.11,12.3400,0.061700,0.0,2021-08-29T01:32:50Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
43,2023-03-23T03:49:59Z,4244,21527.90,12.3500,0.061750,0.0,2021-08-29T01:15:26Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
44,2023-03-23T03:34:11Z,24136,22334.11,12.8100,0.064050,0.0,2021-08-29T02:41:07Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
45,2023-03-23T03:29:11Z,8928,21443.22,12.3400,0.061700,0.0,2021-08-29T01:29:26Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
46,2023-03-23T03:23:23Z,15768,21523.09,12.3500,0.061750,0.0,2022-03-16T23:38:59Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub
47,2023-03-23T03:22:35Z,29676,21533.58,12.3500,0.061750,0.0,2021-08-31T17:20:48Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub
48,2023-03-23T02:58:47Z,12974,21538.03,12.3500,0.061750,0.0,2022-01-17T15:36:12Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub
49,2023-03-23T02:07:47Z,2325,21406.28,12.3600,0.061800,0.0,2021-08-29T01:04:57Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub

In [6]:
# 3. Extracting Properties
def extract_trait_value(properties, trait):
    for prop in properties:
        if prop['trait_type'] == trait:
            return prop['value']
    return None

properties = ['Background', 'Fur', 'Eyes', 'Clothes', 'Hat', 'Mouth', 'Earring']
for prop in properties:
    data[prop] = data['properties'].apply(lambda x: extract_trait_value(json.loads(x), prop))

In [7]:
# 4. Rarity Scores
total_nfts_per_collection = data['collection_name'].value_counts()
for trait in properties:
    trait_counts = data.groupby(['collection_name', trait]).size()
    rarity_score = (1 / trait_counts).reset_index().rename({0: f'{trait}_rarity_score'}, axis=1)
    for index, row in rarity_score.iterrows():
        collection = row['collection_name']
        rarity_score.at[index, f'{trait}_rarity_score'] = row[f'{trait}_rarity_score'] * total_nfts_per_collection[collection]
    data = pd.merge(data, rarity_score, on=['collection_name', trait], how='left')

In [8]:
# Sort the data by token_id, collection_name, and timestamp
data = data.sort_values(by=['token_id', 'collection_name', 'timestamp'])

# Determine the timestamp of the first sale for each NFT
data['first_sale_timestamp'] = data.groupby(['token_id', 'collection_name'])['timestamp'].transform('first')

# Update the transaction_type based on the new logic
data['transaction_type'] = np.where(data['timestamp'] == data['first_sale_timestamp'], 'sale', 'resale')

# Drop the temporary column
data.drop('first_sale_timestamp', axis=1, inplace=True)

In [14]:
data.head(50)

,timestamp,token_id,usd_price,eth_price,royalty_fee,platform_fee,minted_timestamp,properties,collection_name,Background,...,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,transaction_type,resale_value,median_resale_price
52367,2021-09-03 02:03:48+00:00,1,26236.07,7.000,0.175000,0.175000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub,M1 Gray,...,9.414399,14.691580,33.468214,48.319234,89.694815,21.976044,NaN,sale,0.00,26236.070
48147,2021-10-09 19:40:23+00:00,2,71858.40,20.000,0.500000,0.500000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,9.148383,8.258628,6.963883,31.256582,74.287117,4.828455,NaN,sale,0.00,48823.580
33626,2022-03-03 12:29:01+00:00,2,48053.48,16.400,0.410000,0.410000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,9.148383,8.258628,6.963883,31.256582,74.287117,4.828455,NaN,resale,-23804.92,48823.580
32356,2022-03-17 16:54:29+00:00,2,49593.68,17.750,0.443750,0.443750,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,9.148383,8.258628,6.963883,31.256582,74.287117,4.828455,NaN,resale,1540.20,48823.580
22882,2022-08-15 07:17:41+00:00,2,42051.90,22.000,0.550000,0.550000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,9.148383,8.258628,6.963883,31.256582,74.287117,4.828455,NaN,resale,-7541.78,48823.580
60065,2021-08-29 01:54:46+00:00,3,13081.68,4.000,0.100000,0.100000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,sale,0.00,19621.140
59973,2021-08-29 01:58:37+00:00,3,19621.14,6.000,0.150000,0.150000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,6539.46,19621.140
58595,2021-08-29 03:18:29+00:00,3,16137.40,5.000,0.125000,0.125000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,-3483.74,19621.140
56671,2021-08-29 08:08:30+00:00,3,25424.18,7.900,0.197500,0.197500,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,9286.78,19621.140
53573,2021-08-31 13:37:16+00:00,3,21184.84,6.200,0.155000,0.155000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,-4239.34,19621.140
29748,2022-04-20 19:27:53+00:00,3,96739.02,31.500,0.787500,0.630000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,75554.18,19621.140
29057,2022-04-26 05:33:56+00:00,3,120288.80,40.000,1.000000,1.000000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,23549.78,19621.140
18702,2022-12-08 13:24:35+00:00,3,17163.06,13.850,0.346250,0.346250,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,-103125.74,19621.140
18697,2022-12-08 16:11:11+00:00,3,17905.60,14.300,0.000000,0.000000,2021-08-29T00:42:17Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,15.004709,34.956120,NaN,51.395586,6.998497,NaN,resale,742.54,19621.140
62664,2023-01-22 00:30:23+00:00,5,317342.22,194.200,0.000000,0.000000,2021-04-22T23:13:40Z,"[{""trait_type"":""Hat"",""value"":""Bayc Flipped Bri...",BoredApeYachtClub,Army Green,...,7.867246,6.751966,36.997790,90.986413,65.269006,16.518500,NaN,sale,0.00,317342.220
56608,2021-08-29 08:27:59+00:00,5,24111.45,7.500,0.187500,0.187500,2021-08-29T00:43:04Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,9.278774,7.915283,33.468214,38.391883,74.105263,22.299816,NaN,sale,0.00,22314.640
53726,2021-08-31 04:32:21+00:00,5,22314.64,6.890,0.172250,0.172250,2021-08-29T00:43:04Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,9.278774,7.915283,33.468214,38.391883,74.105263,22.299816,NaN,resale,-1796.81,22314.640
52063,2021-09-04 08:32:13+00:00,5,19677.10,5.000,0.125000,0.125000,2021-08-29T00:43:04Z,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,9.278774,7.915283,33.468214,38.391883,74.105263,22.299816,NaN,resale,-2637.54,22314.640
80486,2021-06-21 15:56:28+00:00,6,19787.80,10.000,0.250000,0.250000,2021-04-22T23:13:40Z,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,7.772284,13.271106,16.683109,81.865526,38.486207,4.320945,NaN,sale,0.00,93989.340
70719,2021-12-22 19:16:09+00:00,6,251097.21,63.000,1.575000,1.575000,2021-04-22T23:13:40Z,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,7.772284,13.271106,16.683109,81.865526,38.486207,4.320945,NaN,resale,231309.41,93989.340
66262,2022-07-03 16:40:36+00:00,6,93989.34,89.000,2.225000,2.225000,2021-04-22T23:13:40Z,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,7.772284,13.271106,16.683109,81.865526,38.486207,4.320945,NaN,resale,-157107.87,93989.340
59399,2021-08-29 02:24:10+00:00,6,19659.30,6.000,0.150000,0.150000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,9.873451,13.800775,86.000000,30.905564,144.152381,29.361785,sale,0.00,31965.500
57094,2021-08-29 06:35:05+00:00,6,31965.50,10.000,0.250000,0.250000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,9.873451,13.800775,86.000000,30.905564,144.152381,29.361785,resale,12306.20,31965.500
36543,2022-01-21 01:42:17+00:00,6,79483.14,27.000,0.675000,0.675000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,9.873451,13.800775,86.000000,30.905564,144.152381,29.361785,resale,47517.64,31965.500
56545,2021-08-29 08:59:29+00:00,7,24388.02,7.600,0.190000,0.190000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,sale,0.00,32975.730
50903,2021-09-12 03:01:37+00:00,7,11826.83,3.600,0.090000,0.090000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,resale,-12561.19,32975.730
50340,2021-09-16 15:01:25+00:00,7,17691.65,4.950,0.123750,0.123750,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,resale,5864.82,32975.730
47923,2021-10-13 06:40:43+00:00,7,41563.44,12.000,0.300000,0.300000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,resale,23871.79,32975.730
38384,2022-01-03 03:12:26+00:00,7,61933.48,16.300,0.407500,0.407500,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,resale,20370.04,32975.730
37250,2022-01-12 05:07:27+00:00,7,55911.00,17.300,0.432500,0.432500,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,32.638275,115.541985,19.087011,18.380085,NaN,resale,-6022.48,32975.730
65263,2022-10-21 00:56:23+00:00,8,141331.30,110.000,2.750000,2.750000,2021-04-22T23:13:40Z,"[{""trait_type"":""Mouth"",""value"":""Bored""},{""trai...",BoredApeYachtClub,Aquamarine,...,7.732794,39.860714,33.924012,NaN,17.393766,4.320945,25.404401,sale,0.00,141331.300
56271,2021-08-29 10:38:54+00:00,8,28157.45,8.800,0.220000,0.220000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,16.892857,13.756873,57.279092,76.155975,4.828455,NaN,sale,0.00,38518.060
36403,2022-01-22 22:35:28+00:00,8,33296.59,13.880,0.347000,0.347000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,16.892857,13.756873,57.279092,76.155975,4.828455,NaN,resale,5139.14,38518.060
36240,2022-01-25 00:40:24+00:00,8,43739.53,17.987,0.449675,0.449675,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,16.892857,13.756873,57.279092,76.155975,4.828455,NaN,resale,10442.94,38518.060
35787,2022-01-26 18:35:34+00:00,8,62614.06,24.400,0.610000,0.610000,2021-08-29T00:43:16Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,16.892857,13.756873,57.279092,76.155975,4.828455,NaN,resale,18874.53,38518.060
68143,2022-04-02 09:26:11+00:00,9,469192.50,135.000,3.375000,3.375000,2021-04-22T23:13:40Z,"[{""trait_type"":""Earring"",""value"":""Silver Stud""...",BoredApeYachtClub,Purple,...,7.759676,6.751966,12.897920,55.070724,21.699935,38.179019,12.215615,sale,0.00,331682.750
66845,2022-05-31 20:44:44+00:00,9,194173.00,100.000,2.500000,2.500000,2021-04-22T23:13:40Z,"[{""trait_type"":""Earring"",""value"":""Silver Stud""...",BoredApeYachtClub,Purple,...,7.759676,6.751966,12.897920,55.070724,21.699935,38.179019,12.215615,resale,-275019.50,331682.750
51157,2021-09-09 15:30:29+00:00,9,18459.05,5.250,0.131250,0.131250,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,6.963883,27.797980,39.493803,144.152381,NaN,sale,0.00,47527.010
33377,2022-03-09 17:38:22+00:00,9,48060.25,17.500,0.437500,0.437500,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,6.963883,27.797980,39.493803,144.152381,NaN,resale,29601.20,47527.010
32237,2022-03-18 08:27:06+00:00,9,60730.63,21.650,0.541250,0.541250,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,6.963883,27.797980,39.493803,144.152381,NaN,resale,12670.38,47527.010
25530,2022-06-01 20:38:00+00:00,9,46993.77,26.500,0.662500,0.530000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,9.597971,30.046650,6.963883,27.797980,39.493803,144.152381,NaN,resale,-13736.86,47527.010
71505,2021-11-15 20:47:36+00:00,10,365683.20,80.000,2.000000,2.000000,2021-04-22T23:13:40Z,"[{""trait_type"":""Clothes"",""value"":""Navy Striped...",BoredApeYachtClub,Aquamarine,...,7.732794,64.514451,31.351124,29.683511,114.667808,4.320945,NaN,sale,0.00,365683.200
56452,2021-08-29 09:39:19+00:00,10,24911.95,7.800,0.195000,0.195000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,24.472110,44.257310,84.088889,NaN,6.998497,NaN,sale,0.00,24911.950
55227,2021-08-29 20:26:49+00:00,10,22668.87,7.000,0.175000,0.175000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,24.472110,44.257310,84.088889,NaN,6.998497,NaN,resale,-2243.08,24911.950
42740,2021-11-27 21:53:57+00:00,10,32584.32,8.000,0.200000,0.200000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,8.731468,24.472110,44.257310,84.088889,NaN,6.998497,NaN,resale,9915.45,24911.950
76157,2021-08-04 00:15:11+00:00,11,49835.40,20.000,0.500000,0.500000,2021-04-22T23:13:40Z,"[{""trait_type"":""Background"",""value"":""Gray""},{""...",BoredApeYachtClub,Gray,...,8.585385,7.110427,11.975322,51.197248,180.016129,24.386744,NaN,sale,0.00,49835.400
50862,2021-09-12 17:35:00+00:00,12,23948.33,7.000,0.175000,0.175000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,52.464471,104.386207,205.931973,291.076923,NaN,94.896552,84.676923,sale,0.00,72197.530
38508,2022-01-02 20:00:10+00:00,12,72197.53,19.000,0.475000,0.475000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,52.464471,104.386207,205.931973,291.076923,NaN,94.896552,84.676923,resale,48249.20,72197.530
29997,2022-04-19 11:45:21+00:00,12,100241.91,32.880,0.822000,0.822000,2021-08-29T00:43:33Z,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,52.464471,104.386207,205.931973,291.076923,NaN,94.896552,84.676923,resale,28044.38,72197.530
88818,2021-05-05 20:05:40+00:00,13,3472.59,1.000,0.025000,0.025000,2021-04-22T23:13:40Z,"[{""trait_type"":""Fur"",""value"":""Black""},{""trait_...",BoredApeYachtClub,Yellow,...,7.772284,7.402830,18.227001,39.391765,69.756250,4.320945,NaN,sale,0.00,138344.415

In [10]:
# 5. Transaction Type and Resale Value Calculation
#data['transaction_type'] = np.where(data['timestamp'] > data['minted_timestamp'], 'resale', 'minted')
#data['resale_value'] = data.groupby(['token_id', 'collection_name'])['usd_price'].diff().fillna(0)
#data['historical_median_price_corrected'] = data[data['transaction_type'] == 'resale'].groupby(['token_id', 'collection_name'])['usd_price'].transform('median')

# For 'sale' transactions, set resale_value_corrected to 0
data.loc[data['transaction_type'] == 'sale', 'resale_value'] = 0

# For 'resale' transactions, compute the difference from the previous transaction's usd_price
data.loc[data['transaction_type'] == 'resale', 'resale_value'] = data.groupby(['token_id', 'collection_name'])['usd_price'].diff().fillna(0)

# Historical Median Price Calculation:
#data['_median_resale_price'] = data[data['transaction_type'] == 'resale'].groupby(['token_id', 'collection_name'])['usd_price'].transform('median')

In [13]:

# Convert 'timestamp' column to datetime format
data['timestamp'] = pd.to_datetime(data['timestamp'])

# Sort the data by timestamp, token_id, and collection_name
data = data.sort_values(by=['token_id', 'collection_name', 'timestamp'])

# Compute the corrected median resale price
data['median_resale_price'] = data.groupby(['token_id', 'collection_name'])['usd_price'].transform('median')

In [15]:
# Assuming 'timestamp' and 'minted_timestamp' are in string format
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['minted_timestamp'] = pd.to_datetime(data['minted_timestamp'])

# 6. Time Features
data['days_to_first_resale'] = (data.groupby(['token_id', 'collection_name'])['timestamp'].transform('min') - data['minted_timestamp']).dt.days
data['days_since_minting'] = (data['timestamp'] - data['minted_timestamp']).dt.days
data['transaction_frequency'] = data.groupby(['token_id', 'collection_name'])['timestamp'].transform('count')

In [16]:
# 7. Price Volatility
data['price_volatility'] = data[data['transaction_type'] == 'resale'].groupby(['token_id', 'collection_name'])['usd_price'].transform('std')

In [17]:
# 8. Seasonality and Time Features
data['timestamp'] = pd.to_datetime(data['timestamp'])
data['month'] = data['timestamp'].dt.strftime('%B')
data['day_of_week'] = data['timestamp'].dt.strftime('%A')

In [18]:
from sklearn.linear_model import LinearRegression

# Filter the data to consider only resale transactions
resale_data_temp = data[data['transaction_type'] == 'resale'].copy()

def calculate_trend(prices):
    if len(prices) < 2:
        return 'stable'
    x = np.arange(len(prices)).reshape(-1, 1)
    model = LinearRegression().fit(x, prices)
    if model.coef_ > 0:
        return 'upward'
    elif model.coef_ < 0:
        return 'downward'
    else:
        return 'stable'

# Calculating the trend using the usd_price values of resale transactions
resale_data_temp['linear_regression_trend'] = resale_data_temp.groupby(['token_id', 'collection_name'])['usd_price'].transform(lambda x: calculate_trend(x.tolist()))

# Creating a mapping of (token_id, collection_name) to its linear_regression_trend
trend_mapping = resale_data_temp.drop_duplicates(['token_id', 'collection_name']).set_index(['token_id', 'collection_name'])['linear_regression_trend'].to_dict()

# Updating the data DataFrame directly with this trend information
data['linear_regression_trend'] = data.set_index(['token_id', 'collection_name']).index.map(trend_mapping.get)
data['linear_regression_trend'] = data['linear_regression_trend'].fillna('stable')  # Fill NaNs with 'stable'

In [19]:
data.head(50)

,timestamp,token_id,usd_price,eth_price,royalty_fee,platform_fee,minted_timestamp,properties,collection_name,Background,...,transaction_type,resale_value,median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,month,day_of_week,linear_regression_trend
52367,2021-09-03 02:03:48+00:00,1,26236.07,7.000,0.175000,0.175000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Gray""}...",MutantApeYachtClub,M1 Gray,...,sale,0.00,26236.070,5,5,1,NaN,September,Friday,stable
48147,2021-10-09 19:40:23+00:00,2,71858.40,20.000,0.500000,0.500000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,sale,0.00,48823.580,41,41,4,NaN,October,Saturday,downward
33626,2022-03-03 12:29:01+00:00,2,48053.48,16.400,0.410000,0.410000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,resale,-23804.92,48823.580,41,186,4,3984.754783,March,Thursday,downward
32356,2022-03-17 16:54:29+00:00,2,49593.68,17.750,0.443750,0.443750,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,resale,1540.20,48823.580,41,200,4,3984.754783,March,Thursday,downward
22882,2022-08-15 07:17:41+00:00,2,42051.90,22.000,0.550000,0.550000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Blue,...,resale,-7541.78,48823.580,41,351,4,3984.754783,August,Monday,downward
60065,2021-08-29 01:54:46+00:00,3,13081.68,4.000,0.100000,0.100000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,sale,0.00,19621.140,0,0,9,NaN,August,Sunday,upward
59973,2021-08-29 01:58:37+00:00,3,19621.14,6.000,0.150000,0.150000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,6539.46,19621.140,0,0,9,41748.107686,August,Sunday,upward
58595,2021-08-29 03:18:29+00:00,3,16137.40,5.000,0.125000,0.125000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,-3483.74,19621.140,0,0,9,41748.107686,August,Sunday,upward
56671,2021-08-29 08:08:30+00:00,3,25424.18,7.900,0.197500,0.197500,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,9286.78,19621.140,0,0,9,41748.107686,August,Sunday,upward
53573,2021-08-31 13:37:16+00:00,3,21184.84,6.200,0.155000,0.155000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,-4239.34,19621.140,0,2,9,41748.107686,August,Tuesday,upward
29748,2022-04-20 19:27:53+00:00,3,96739.02,31.500,0.787500,0.630000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,75554.18,19621.140,0,234,9,41748.107686,April,Wednesday,upward
29057,2022-04-26 05:33:56+00:00,3,120288.80,40.000,1.000000,1.000000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,23549.78,19621.140,0,240,9,41748.107686,April,Tuesday,upward
18702,2022-12-08 13:24:35+00:00,3,17163.06,13.850,0.346250,0.346250,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,-103125.74,19621.140,0,466,9,41748.107686,December,Thursday,upward
18697,2022-12-08 16:11:11+00:00,3,17905.60,14.300,0.000000,0.000000,2021-08-29 00:42:17+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,742.54,19621.140,0,466,9,41748.107686,December,Thursday,upward
62664,2023-01-22 00:30:23+00:00,5,317342.22,194.200,0.000000,0.000000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Hat"",""value"":""Bayc Flipped Bri...",BoredApeYachtClub,Army Green,...,sale,0.00,317342.220,639,639,1,NaN,January,Sunday,stable
56608,2021-08-29 08:27:59+00:00,5,24111.45,7.500,0.187500,0.187500,2021-08-29 00:43:04+00:00,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,sale,0.00,22314.640,0,0,3,NaN,August,Sunday,downward
53726,2021-08-31 04:32:21+00:00,5,22314.64,6.890,0.172250,0.172250,2021-08-29 00:43:04+00:00,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,resale,-1796.81,22314.640,0,2,3,1865.022420,August,Tuesday,downward
52063,2021-09-04 08:32:13+00:00,5,19677.10,5.000,0.125000,0.125000,2021-08-29 00:43:04+00:00,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Army Green,...,resale,-2637.54,22314.640,0,6,3,1865.022420,September,Saturday,downward
80486,2021-06-21 15:56:28+00:00,6,19787.80,10.000,0.250000,0.250000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,sale,0.00,93989.340,59,59,3,NaN,June,Monday,downward
70719,2021-12-22 19:16:09+00:00,6,251097.21,63.000,1.575000,1.575000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,resale,231309.41,93989.340,59,243,3,111092.040255,December,Wednesday,downward
66262,2022-07-03 16:40:36+00:00,6,93989.34,89.000,2.225000,2.225000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Clothes"",""value"":""Tweed Suit""}...",BoredApeYachtClub,Yellow,...,resale,-157107.87,93989.340,59,436,3,111092.040255,July,Sunday,downward
59399,2021-08-29 02:24:10+00:00,6,19659.30,6.000,0.150000,0.150000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,sale,0.00,31965.500,0,0,3,NaN,August,Sunday,upward
57094,2021-08-29 06:35:05+00:00,6,31965.50,10.000,0.250000,0.250000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,12306.20,31965.500,0,0,3,33600.045470,August,Sunday,upward
36543,2022-01-21 01:42:17+00:00,6,79483.14,27.000,0.675000,0.675000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,47517.64,31965.500,0,145,3,33600.045470,January,Friday,upward
56545,2021-08-29 08:59:29+00:00,7,24388.02,7.600,0.190000,0.190000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,sale,0.00,32975.730,0,0,6,NaN,August,Sunday,upward
50903,2021-09-12 03:01:37+00:00,7,11826.83,3.600,0.090000,0.090000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,-12561.19,32975.730,0,14,6,22380.498624,September,Sunday,upward
50340,2021-09-16 15:01:25+00:00,7,17691.65,4.950,0.123750,0.123750,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,5864.82,32975.730,0,18,6,22380.498624,September,Thursday,upward
47923,2021-10-13 06:40:43+00:00,7,41563.44,12.000,0.300000,0.300000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,23871.79,32975.730,0,45,6,22380.498624,October,Wednesday,upward
38384,2022-01-03 03:12:26+00:00,7,61933.48,16.300,0.407500,0.407500,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,20370.04,32975.730,0,127,6,22380.498624,January,Monday,upward
37250,2022-01-12 05:07:27+00:00,7,55911.00,17.300,0.432500,0.432500,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,-6022.48,32975.730,0,136,6,22380.498624,January,Wednesday,upward
65263,2022-10-21 00:56:23+00:00,8,141331.30,110.000,2.750000,2.750000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Mouth"",""value"":""Bored""},{""trai...",BoredApeYachtClub,Aquamarine,...,sale,0.00,141331.300,546,546,1,NaN,October,Friday,stable
56271,2021-08-29 10:38:54+00:00,8,28157.45,8.800,0.220000,0.220000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,sale,0.00,38518.060,0,0,4,NaN,August,Sunday,upward
36403,2022-01-22 22:35:28+00:00,8,33296.59,13.880,0.347000,0.347000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,5139.14,38518.060,0,146,4,14859.435419,January,Saturday,upward
36240,2022-01-25 00:40:24+00:00,8,43739.53,17.987,0.449675,0.449675,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,10442.94,38518.060,0,148,4,14859.435419,January,Tuesday,upward
35787,2022-01-26 18:35:34+00:00,8,62614.06,24.400,0.610000,0.610000,2021-08-29 00:43:16+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,18874.53,38518.060,0,150,4,14859.435419,January,Wednesday,upward
68143,2022-04-02 09:26:11+00:00,9,469192.50,135.000,3.375000,3.375000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Earring"",""value"":""Silver Stud""...",BoredApeYachtClub,Purple,...,sale,0.00,331682.750,344,344,2,NaN,April,Saturday,stable
66845,2022-05-31 20:44:44+00:00,9,194173.00,100.000,2.500000,2.500000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Earring"",""value"":""Silver Stud""...",BoredApeYachtClub,Purple,...,resale,-275019.50,331682.750,344,403,2,NaN,May,Tuesday,stable
51157,2021-09-09 15:30:29+00:00,9,18459.05,5.250,0.131250,0.131250,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,sale,0.00,47527.010,11,11,4,NaN,September,Thursday,downward
33377,2022-03-09 17:38:22+00:00,9,48060.25,17.500,0.437500,0.437500,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,29601.20,47527.010,11,192,4,7641.740984,March,Wednesday,downward
32237,2022-03-18 08:27:06+00:00,9,60730.63,21.650,0.541250,0.541250,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,12670.38,47527.010,11,201,4,7641.740984,March,Friday,downward
25530,2022-06-01 20:38:00+00:00,9,46993.77,26.500,0.662500,0.530000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Aquamarine,...,resale,-13736.86,47527.010,11,276,4,7641.740984,June,Wednesday,downward
71505,2021-11-15 20:47:36+00:00,10,365683.20,80.000,2.000000,2.000000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Clothes"",""value"":""Navy Striped...",BoredApeYachtClub,Aquamarine,...,sale,0.00,365683.200,206,206,1,NaN,November,Monday,stable
56452,2021-08-29 09:39:19+00:00,10,24911.95,7.800,0.195000,0.195000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,sale,0.00,24911.950,0,0,3,NaN,August,Sunday,upward
55227,2021-08-29 20:26:49+00:00,10,22668.87,7.000,0.175000,0.175000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,-2243.08,24911.950,0,0,3,7011.281934,August,Sunday,upward
42740,2021-11-27 21:53:57+00:00,10,32584.32,8.000,0.200000,0.200000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Yellow,...,resale,9915.45,24911.950,0,90,3,7011.281934,November,Saturday,upward
76157,2021-08-04 00:15:11+00:00,11,49835.40,20.000,0.500000,0.500000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Background"",""value"":""Gray""},{""...",BoredApeYachtClub,Gray,...,sale,0.00,49835.400,103,103,1,NaN,August,Wednesday,stable
50862,2021-09-12 17:35:00+00:00,12,23948.33,7.000,0.175000,0.175000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,sale,0.00,72197.530,14,14,3,NaN,September,Sunday,upward
38508,2022-01-02 20:00:10+00:00,12,72197.53,19.000,0.475000,0.475000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,resale,48249.20,72197.530,14,126,3,19830.371272,January,Sunday,upward
29997,2022-04-19 11:45:21+00:00,12,100241.91,32.880,0.822000,0.822000,2021-08-29 00:43:33+00:00,"[{""trait_type"":""Background"",""value"":""M2 Blue""}...",MutantApeYachtClub,M2 Blue,...,resale,28044.38,72197.530,14,233,3,19830.371272,April,Tuesday,upward
88818,2021-05-05 20:05:40+00:00,13,3472.59,1.000,0.025000,0.025000,2021-04-22 23:13:40+00:00,"[{""trait_type"":""Fur"",""value"":""Black""},{""trait_...",BoredApeYachtClub,Yellow,...,sale,0.00,138344.415,12,12,2,NaN,May,Wednesday,stable

In [20]:
data.shape

(94027, 33)

In [20]:
drop_cols2 = ['properties']
data = data.drop(columns=drop_cols2, errors='ignore')
drop_col3 = ['eth_price']
data = data.drop(columns=drop_col3, errors='ignore')

In [21]:
data.head()

,timestamp,token_id,usd_price,royalty_fee,platform_fee,minted_timestamp,collection_name,Background,Fur,Eyes,...,transaction_type,resale_value,_median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,month,day_of_week,linear_regression_trend
52367,2021-09-03 02:03:48+00:00,1,26236.07,0.17500,0.17500,2021-08-29 00:42:17+00:00,MutantApeYachtClub,M1 Gray,M1 Cream,M1 Eyepatch,...,sale,0.00,NaN,5,5,1,NaN,September,Friday,stable
48147,2021-10-09 19:40:23+00:00,2,71858.40,0.50000,0.50000,2021-08-29 00:42:17+00:00,MutantApeYachtClub,M1 Blue,M1 Brown,M1 Bored,...,sale,0.00,NaN,41,41,4,NaN,October,Saturday,downward
33626,2022-03-03 12:29:01+00:00,2,48053.48,0.41000,0.41000,2021-08-29 00:42:17+00:00,MutantApeYachtClub,M1 Blue,M1 Brown,M1 Bored,...,resale,-23804.92,48053.48,41,186,4,3984.754783,March,Thursday,downward
32356,2022-03-17 16:54:29+00:00,2,49593.68,0.44375,0.44375,2021-08-29 00:42:17+00:00,MutantApeYachtClub,M1 Blue,M1 Brown,M1 Bored,...,resale,1540.20,48053.48,41,200,4,3984.754783,March,Thursday,downward
22882,2022-08-15 07:17:41+00:00,2,42051.90,0.55000,0.55000,2021-08-29 00:42:17+00:00,MutantApeYachtClub,M1 Blue,M1 Brown,M1 Bored,...,resale,-7541.78,48053.48,41,351,4,3984.754783,August,Monday,downward

In [22]:
data.shape

(94027, 31)

In [24]:
corr_matrix = data.corr(method='spearman')
corr_matrix['usd_price'].sort_values(ascending=False)

usd_price                  1.000000
royalty_fee                0.690742
_median_resale_price       0.661830
platform_fee               0.529615
days_since_minting         0.452899
price_volatility           0.353787
resale_value               0.341852
days_to_first_resale       0.150791
Hat_rarity_score           0.090275
Background_rarity_score    0.087330
Clothes_rarity_score       0.086839
Mouth_rarity_score         0.086615
Earring_rarity_score       0.084096
Eyes_rarity_score          0.079560
Fur_rarity_score           0.077828
transaction_frequency      0.043531
token_id                   0.012076
Name: usd_price, dtype: float64

In [24]:
data.shape

(94027, 32)

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94027 entries, 52367 to 22558
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                94027 non-null  datetime64[ns, UTC]
 1   token_id                 94027 non-null  int64
 2   usd_price                94027 non-null  float64
 3   royalty_fee              94027 non-null  float64
 4   platform_fee             94027 non-null  float64
 5   minted_timestamp         94027 non-null  datetime64[ns, UTC]
 6   collection_name          94027 non-null  object
 7   Background               94023 non-null  object
 8   Fur                      94023 non-null  object
 9   Eyes                     94023 non-null  object
 10  Clothes                  77229 non-null  object
 11  Hat                      71443 non-null  object
 12  Mouth                    94023 non-null  object
 13  Earring                  25171 non-null  object
 14  Background_rarity_score  94023 non-null  float64
 15  Fur_rarity_score         94023 non-null  float64
 16  Eyes_rarity_score        94023 non-null  float64
 17  Clothes_rarity_score     77229 non-null  float64
 18  Hat_rarity_score         71443 non-null  float64
 19  Mouth_rarity_score       94023 non-null  float64
 20  Earring_rarity_score     25171 non-null  float64
 21  transaction_type         94027 non-null  object
 22  resale_value             94027 non-null  float64
 23  _median_resale_price     71183 non-null  float64
 24  days_to_first_resale     94027 non-null  int64
 25  days_since_minting       94027 non-null  int64
 26  transaction_frequency    94027 non-null  int64
 27  price_volatility         66462 non-null  float64
 28  month                    94027 non-null  object
 29  day_of_week              94027 non-null  object
 30  linear_regression_trend  94027 non-null  object
dtypes: datetime64[ns, UTC](2), float64(13), int64(4), object(12)
memory usage: 23.0+ MB

In [26]:
data.isnull().sum()

timestamp                      0
token_id                       0
usd_price                      0
royalty_fee                    0
platform_fee                   0
minted_timestamp               0
collection_name                0
Background                     4
Fur                            4
Eyes                           4
Clothes                    16798
Hat                        22584
Mouth                          4
Earring                    68856
Background_rarity_score        4
Fur_rarity_score               4
Eyes_rarity_score              4
Clothes_rarity_score       16798
Hat_rarity_score           22584
Mouth_rarity_score             4
Earring_rarity_score       68856
transaction_type               0
resale_value                   0
_median_resale_price       22844
days_to_first_resale           0
days_since_minting             0
transaction_frequency          0
price_volatility           27565
month                          0
day_of_week                    0
linear_regression_trend        0
dtype: int64

In [21]:
data.to_csv("Feature_final_dataset1.csv", index=False)

# ML Model

In [22]:
df = data[data['transaction_type'] == 'resale']
print(df)

                      timestamp  token_id  usd_price  eth_price  royalty_fee  \
33626 2022-03-03 12:29:01+00:00         2   48053.48      16.40      0.41000
32356 2022-03-17 16:54:29+00:00         2   49593.68      17.75      0.44375
22882 2022-08-15 07:17:41+00:00         2   42051.90      22.00      0.55000
59973 2021-08-29 01:58:37+00:00         3   19621.14       6.00      0.15000
58595 2021-08-29 03:18:29+00:00         3   16137.40       5.00      0.12500
...                         ...       ...        ...        ...          ...
12241 2023-01-21 04:34:35+00:00     29960   23135.26      13.99      0.06995
12484 2023-01-19 06:11:35+00:00     29982   20474.40      13.40      0.33500
12479 2023-01-19 08:08:59+00:00     29982   20731.36      13.55      0.06775
12472 2023-01-19 08:49:35+00:00     29982   21378.12      13.99      0.06995
12469 2023-01-19 09:34:11+00:00     29983   28148.99      18.49      0.46225

       platform_fee          minted_timestamp  \
33626       0.41000 2021-08-29 00:42:17+00:00
32356       0.44375 2021-08-29 00:42:17+00:00
22882       0.55000 2021-08-29 00:42:17+00:00
59973       0.15000 2021-08-29 00:42:17+00:00
58595       0.12500 2021-08-29 00:42:17+00:00
...             ...                       ...
12241       0.00000 2022-04-26 00:50:34+00:00
12484       0.33500 2022-05-02 03:51:40+00:00
12479       0.00000 2022-05-02 03:51:40+00:00
12472       0.20985 2022-05-02 03:51:40+00:00
12469       0.00000 2022-04-25 12:52:31+00:00

                                              properties     collection_name  \
33626  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
32356  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
22882  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
59973  [{"trait_type":"Background","value":"M1 Yellow...  MutantApeYachtClub
58595  [{"trait_type":"Background","value":"M1 Yellow...  MutantApeYachtClub
...                                                  ...                 ...
12241  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
12484  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
12479  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
12472  [{"trait_type":"Background","value":"M1 Blue"}...  MutantApeYachtClub
12469  [{"trait_type":"Background","value":"M2 Blue"}...  MutantApeYachtClub

      Background  ... transaction_type resale_value median_resale_price  \
33626    M1 Blue  ...           resale    -23804.92           48823.580
32356    M1 Blue  ...           resale      1540.20           48823.580
22882    M1 Blue  ...           resale     -7541.78           48823.580
59973  M1 Yellow  ...           resale      6539.46           19621.140
58595  M1 Yellow  ...           resale     -3483.74           19621.140
...          ...  ...              ...          ...                 ...
12241    M1 Blue  ...           resale       179.77           23327.320
12484    M1 Blue  ...           resale      1382.88           20602.880
12479    M1 Blue  ...           resale       256.96           20602.880
12472    M1 Blue  ...           resale       646.76           20602.880
12469    M2 Blue  ...           resale      6636.95           24830.515

      days_to_first_resale days_since_minting transaction_frequency  \
33626                   41                186                     4
32356                   41                200                     4
22882                   41                351                     4
59973                    0                  0                     9
58595                    0                  0                     9
...                    ...                ...                   ...
12241                  262                270                     5
12484                  244                262                     4
12479                  244                262                     4
12472                  244                262                     4
12469                  251                268                     2

       price_volatility    month  day_of_week  linear_regression_trend
33626       3984.754783    March     Thursday                 downward
32356       3984.754783    March     Thursday                 downward
22882       3984.754783   August       Monday                 downward
59973      41748.107686   August       Sunday                   upward
58595      41748.107686   August       Sunday                   upward
...                 ...      ...          ...                      ...
12241        822.220945  January     Saturday                 downward
12484        465.660244  January     Thursday                   upward
12479        465.660244  January     Thursday                   upward
12472        465.660244  January     Thursday                   upward
12469               NaN  January     Thursday                   stable

[71183 rows x 33 columns]

In [23]:
df.shape

(71183, 33)

In [24]:
df.isnull().sum()

timestamp                      0
token_id                       0
usd_price                      0
eth_price                      0
royalty_fee                    0
platform_fee                   0
minted_timestamp               0
properties                     0
collection_name                0
Background                     0
Fur                            0
Eyes                           0
Clothes                    12622
Hat                        17461
Mouth                          0
Earring                    52682
Background_rarity_score        0
Fur_rarity_score               0
Eyes_rarity_score              0
Clothes_rarity_score       12622
Hat_rarity_score           17461
Mouth_rarity_score             0
Earring_rarity_score       52682
transaction_type               0
resale_value                   0
median_resale_price            0
days_to_first_resale           0
days_since_minting             0
transaction_frequency          0
price_volatility            4721
month                          0
day_of_week                    0
linear_regression_trend        0
dtype: int64

In [25]:
corr_matrix = data.corr(method='spearman')
corr_matrix['usd_price'].sort_values(ascending=False)

usd_price                  1.000000
eth_price                  0.895478
royalty_fee                0.690742
median_resale_price        0.593572
platform_fee               0.529615
days_since_minting         0.452899
price_volatility           0.353787
resale_value               0.341852
days_to_first_resale       0.150791
Hat_rarity_score           0.090275
Background_rarity_score    0.087330
Clothes_rarity_score       0.086839
Mouth_rarity_score         0.086615
Earring_rarity_score       0.084096
Eyes_rarity_score          0.079560
Fur_rarity_score           0.077828
transaction_frequency      0.043531
token_id                   0.012076
Name: usd_price, dtype: float64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71183 entries, 33626 to 12469
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   token_id                 71183 non-null  int64
 1   usd_price                71183 non-null  float64
 2   royalty_fee              71183 non-null  float64
 3   platform_fee             71183 non-null  float64
 4   properties               71183 non-null  object
 5   collection_name          71183 non-null  object
 6   Eyes                     71183 non-null  object
 7   Background_rarity_score  71183 non-null  float64
 8   Fur_rarity_score         71183 non-null  float64
 9   Eyes_rarity_score        71183 non-null  float64
 10  Clothes_rarity_score     58561 non-null  float64
 11  Hat_rarity_score         53722 non-null  float64
 12  Mouth_rarity_score       71183 non-null  float64
 13  Earring_rarity_score     18501 non-null  float64
 14  transaction_type         71183 non-null  object
 15  resale_value             71183 non-null  float64
 16  median_resale_price      71183 non-null  float64
 17  days_to_first_resale     71183 non-null  int64
 18  days_since_minting       71183 non-null  int64
 19  transaction_frequency    71183 non-null  int64
 20  price_volatility         66462 non-null  float64
 21  linear_regression_trend  71183 non-null  object
dtypes: float64(13), int64(4), object(5)
memory usage: 12.5+ MB

In [27]:
drop_col3 = ['eth_price', 'timestamp','minted_timestamp','Background', 'Fur', 'Eyes', 'Clothes', 'Hat', 'Mouth', 'Earring', 'day_of_week', 'month' ]
df = df.drop(columns=drop_col3, errors='ignore')

In [29]:
# Import library
from sklearn.model_selection import train_test_split

In [30]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=7)
print(f"{train_set.shape[0]} train and {test_set.shape[0]} test instances")

56946 train and 14237 test instances

In [31]:
train_set

,token_id,usd_price,royalty_fee,platform_fee,properties,collection_name,Eyes,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,...,Mouth_rarity_score,Earring_rarity_score,transaction_type,resale_value,median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,linear_regression_trend
53478,7877,19429.16,0.14475,0.14475,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Eyepatch,8.731468,9.873451,33.468214,...,4.828455,NaN,resale,-3081.82,23856.800,0,2,65,18103.825490,downward
12671,9047,21230.68,0.06840,0.00000,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Sleepy,9.597971,16.892857,13.800775,...,6.998497,NaN,resale,-2117.33,21920.530,2,507,13,2652.876804,upward
1451,8279,23261.18,0.07045,0.00000,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Sad,9.148383,7.915283,19.961754,...,6.998497,NaN,resale,-66.22,24182.220,237,564,19,31145.175133,downward
25198,3263,29001.20,0.50000,0.50000,"[{""trait_type"":""Background"",""value"":""M2 Gray""}...",MutantApeYachtClub,M2 Bloodshot,57.387678,61.403651,81.267114,...,43.214847,NaN,resale,-29259.05,29001.200,26,287,5,16476.771863,upward
27801,5512,68156.11,0.59750,0.59750,"[{""trait_type"":""Background"",""value"":""M1 Blue""}...",MutantApeYachtClub,M1 Bored,9.148383,7.915283,6.963883,...,42.487018,NaN,resale,48648.67,67556.035,3,246,4,3690.031437,upward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32898,9772,58686.05,0.53000,0.53000,"[{""trait_type"":""Background"",""value"":""M1 Yellow...",MutantApeYachtClub,M1 Wide Eyed,8.731468,9.873451,20.221777,...,6.998497,NaN,resale,7482.45,56140.080,10,199,6,8245.729841,upward
61983,2093,130356.12,0.00000,0.00000,"[{""trait_type"":""Fur"",""value"":""Brown""},{""trait_...",BoredApeYachtClub,Closed,8.216687,6.751966,12.001075,...,30.301357,11.153564,resale,27582.24,94457.620,2,661,9,42560.341612,upward
31730,9112,62406.76,0.53750,0.53750,"[{""trait_type"":""Background"",""value"":""M1 Army G...",MutantApeYachtClub,M1 Scumbag,9.278774,7.915283,71.061033,...,6.998497,NaN,resale,11023.06,23509.280,0,204,6,20797.240841,upward
28731,15042,114599.20,1.00000,1.00000,"[{""trait_type"":""Background"",""value"":""M1 Aquama...",MutantApeYachtClub,M1 Sleepy,9.597971,27.161956,13.800775,...,4.828455,NaN,resale,70098.88,39790.885,24,142,6,39263.888650,downward
844,18732,24079.50,0.06630,0.00000,"[{""trait_type"":""Background"",""value"":""M1 Orange...",MutantApeYachtClub,M1 Hypnotized,9.721259,15.004709,75.964868,...,4.828455,13.617634,resale,-398.16,23473.010,0,566,38,1400.607612,upward

In [34]:
test_set.head()

,usd_price,royalty_fee,platform_fee,collection_name,Eyes,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,transaction_type,resale_value,median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,linear_regression_trend
88866,1356.84,0.01025,0.01025,BoredApeYachtClub,Bored,7.732794,13.271106,6.049322,44.172823,29.396839,4.320945,11.153564,resale,-27.71,62887.575,1,4,6,100052.118750,upward
46658,20177.22,0.11725,0.11725,MutantApeYachtClub,M2 Sunglasses,56.689139,83.855956,205.931973,NaN,NaN,43.214847,NaN,resale,1466.40,23819.865,10,64,6,21203.834326,upward
2286,21712.89,0.07340,0.00000,MutantApeYachtClub,M1 Zombie,9.278774,22.152945,34.956120,48.319234,50.453333,51.791275,16.149373,resale,-13209.73,28317.755,78,559,2,NaN,stable
66703,145619.00,2.50000,2.50000,BoredApeYachtClub,Sleepy,8.198580,7.110427,12.897920,101.463636,61.436697,6.065761,NaN,resale,-198527.07,145619.000,50,406,7,142771.798304,upward
51038,13629.22,0.10250,0.10250,MutantApeYachtClub,M1 Eyepatch,9.278774,15.004709,33.468214,51.048904,NaN,16.266523,NaN,resale,-5176.09,24611.915,0,12,20,19291.293956,downward

In [35]:
test_set.drop("transaction_type", axis=1, inplace=True)
train_set.drop("transaction_type", axis=1, inplace=True)

In [42]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

one_hot_encoder = OneHotEncoder(drop="first", sparse=False)

# categorical columns to transform
cat_cols = ['linear_regression_trend', 'collection_name', 'Eyes']

# fit an encoder and transform the trainset
cat_vals = train_set[cat_cols].to_numpy()
transformed = one_hot_encoder.fit_transform(cat_vals)

# the names of the new columns are the unique values of the categorical columns
new_col_names = one_hot_encoder.get_feature_names_out(input_features=cat_cols)

# put the transformed data as columns in the trainset dataframe
train_set[new_col_names] = transformed

# check if the dummies are produced correctly in the trainset
train_set.head()

C:\Users\USER\anaconda3\New folder\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,usd_price,royalty_fee,platform_fee,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,...,Eyes_M2 X Eyes,Eyes_M2 Zombie,Eyes_Robot,Eyes_Sad,Eyes_Scumbag,Eyes_Sleepy,Eyes_Sunglasses,Eyes_Wide Eyed,Eyes_X Eyes,Eyes_Zombie
0,-0.138063,-0.044017,0.010326,-0.333682,-0.289441,0.685213,-0.238318,NaN,-0.364790,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.103432,-0.233354,-0.304348,0.285518,0.132238,-0.312560,0.070207,-0.284386,-0.306376,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.064399,-0.228270,-0.304348,-0.035756,-0.407074,0.000000,-0.002185,-0.322706,-0.306376,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.045943,0.836950,0.782609,34.435878,2.806145,3.110157,5.349820,NaN,0.668516,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.798630,1.078735,0.994565,-0.035756,-0.407074,-0.659411,0.070207,-0.315277,0.648924,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
# transform the **testset** using the encoder fitted on trainset
cat_vals = test_set[cat_cols].to_numpy()
transformed = one_hot_encoder.transform(cat_vals)

# put the transformed data as columns in the testset dataframe
for i, new_col_name in enumerate(new_col_names):
    test_set[new_col_name] = transformed[:,i]
    
# check if the dummies are produced correctly in the testset
test_set.head()

,usd_price,royalty_fee,platform_fee,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,...,Eyes_M2 X Eyes,Eyes_M2 Zombie,Eyes_Robot,Eyes_Sad,Eyes_Scumbag,Eyes_Sleepy,Eyes_Sunglasses,Eyes_Wide Eyed,Eyes_X Eyes,Eyes_Zombie
0,-0.485473,-0.377557,-0.282065,-1.047331,-0.085332,-0.705808,-0.126665,-0.351163,-0.378452,-0.317312,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.123683,-0.112213,-0.049457,33.936704,4.154928,9.434681,NaN,NaN,0.668516,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.094163,-0.220955,-0.304348,0.057421,0.448228,0.760697,-0.010857,0.149680,0.899381,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.287723,5.796652,5.130435,-0.714482,-0.455424,-0.358364,1.473449,0.410926,-0.331484,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,-0.249557,-0.148791,-0.081522,0.057421,0.018811,0.685213,0.065382,NaN,-0.056894,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
from sklearn.preprocessing import RobustScaler

# Create a RobustScaler instance
scaler = RobustScaler()

# Separate the target variable and predictors
trainset_target = train_set[['linear_regression_trend','collection_name','Eyes']].values
trainset_predictors = train_set.drop(['Eyes','linear_regression_trend','collection_name'], axis=1)

# Apply the RobustScaler to the predictor variables
scaled_vals = scaler.fit_transform(trainset_predictors)
train_set = pd.DataFrame(scaled_vals, columns=trainset_predictors.columns)

# Put the non-scaled target variable back in
train_set[['linear_regression_trend','collection_name','Eyes']] = trainset_target

# Inspect the data
train_set.head()

,usd_price,royalty_fee,platform_fee,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,resale_value,median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,linear_regression_trend,collection_name,Eyes
0,-0.138063,-0.044017,0.010326,-0.333682,-0.289441,0.685213,-0.238318,NaN,-0.364790,NaN,-0.349035,-0.051764,-0.092308,-0.608040,6.444444,0.029313,downward,MutantApeYachtClub,M1 Eyepatch
1,-0.103432,-0.233354,-0.304348,0.285518,0.132238,-0.312560,0.070207,-0.284386,-0.306376,NaN,-0.272280,-0.115162,-0.061538,0.660804,0.666667,-0.364381,upward,MutantApeYachtClub,M1 Sleepy
2,-0.064399,-0.228270,-0.304348,-0.035756,-0.407074,0.000000,-0.002185,-0.322706,-0.306376,NaN,-0.109050,-0.041108,3.553846,0.804020,1.333333,0.361610,downward,MutantApeYachtClub,M1 Sad
3,0.045943,0.836950,0.782609,34.435878,2.806145,3.110157,5.349820,NaN,0.668516,NaN,-2.432248,0.116678,0.307692,0.108040,-0.222222,-0.012145,upward,MutantApeYachtClub,M2 Bloodshot
4,0.798630,1.078735,0.994565,-0.035756,-0.407074,-0.659411,0.070207,-0.315277,0.648924,NaN,3.767734,1.379066,-0.046154,0.005025,-0.333333,-0.337954,upward,MutantApeYachtClub,M1 Bored

In [33]:
test_set.drop("token_id", axis=1, inplace=True)
train_set.drop("token_id", axis=1, inplace=True)

test_set.drop("properties", axis=1, inplace=True)
train_set.drop("properties", axis=1, inplace=True)

In [37]:
from sklearn.preprocessing import RobustScaler

# Create a RobustScaler instance
scaler = RobustScaler()

# Fit the transformer on the training set
scaler.fit(trainset_predictors)

# Separate the target variable and predictors in the test set
testset_target = test_set[['linear_regression_trend','collection_name','Eyes']].values
testset_predictors = test_set.drop(['Eyes','linear_regression_trend','collection_name'], axis=1)

# Apply the RobustScaler to the predictor variables in the test set
scaled_vals = scaler.transform(testset_predictors)
test_set = pd.DataFrame(scaled_vals, columns=testset_predictors.columns)

# Put the non-scaled target variable back in the test set DataFrame
test_set[['linear_regression_trend','collection_name','Eyes']] = testset_target

# Inspect the modified test set
test_set.head()

,usd_price,royalty_fee,platform_fee,Background_rarity_score,Fur_rarity_score,Eyes_rarity_score,Clothes_rarity_score,Hat_rarity_score,Mouth_rarity_score,Earring_rarity_score,resale_value,median_resale_price,days_to_first_resale,days_since_minting,transaction_frequency,price_volatility,linear_regression_trend,collection_name,Eyes
0,-0.485473,-0.377557,-0.282065,-1.047331,-0.085332,-0.705808,-0.126665,-0.351163,-0.378452,-0.317312,-0.105986,1.226208,-0.076923,-0.603015,-0.111111,2.117377,upward,BoredApeYachtClub,Bored
1,-0.123683,-0.112213,-0.049457,33.936704,4.154928,9.434681,NaN,NaN,0.668516,NaN,0.012917,-0.052973,0.061538,-0.452261,-0.111111,0.108302,upward,MutantApeYachtClub,M2 Sunglasses
2,-0.094163,-0.220955,-0.304348,0.057421,0.448228,0.760697,-0.010857,0.149680,0.899381,0.000000,-1.155025,0.094300,1.107692,0.791457,-0.555556,NaN,stable,MutantApeYachtClub,M1 Zombie
3,2.287723,5.796652,5.130435,-0.714482,-0.455424,-0.358364,1.473449,0.410926,-0.331484,NaN,-15.902783,3.935055,0.676923,0.407035,0.000000,3.205885,upward,BoredApeYachtClub,Sleepy
4,-0.249557,-0.148791,-0.081522,0.057421,0.018811,0.685213,0.065382,NaN,-0.056894,NaN,-0.515699,-0.027039,-0.092308,-0.582915,1.444444,0.059570,downward,MutantApeYachtClub,M1 Eyepatch

In [45]:
# drop labels for training set, but keep all others
Xtrain = train_set.drop("usd_price", axis=1)

ytrain = train_set["usd_price"].copy()

# drop labels for training set, but keep all others
Xtest = test_set.drop("usd_price", axis=1)

ytest = test_set["usd_price"].copy()

In [47]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(Xtrain, ytrain)
yhat = tree_reg.predict(Xtrain)
tree_mse = mean_squared_error(ytrain, yhat)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

ImportError: cannot import name '_fit_context' from 'sklearn.base' (C:\Users\USER\anaconda3\New folder\lib\site-packages\sklearn\base.py)

In [60]:
print(X_train.isna().sum())
print(y_train.isna().sum())

token_id                       0
royalty_fee                    0
platform_fee                   0
Background_rarity_score        0
Fur_rarity_score               0
Eyes_rarity_score              0
Clothes_rarity_score       10122
Hat_rarity_score           14038
Mouth_rarity_score             0
Earring_rarity_score       42115
resale_value                   0
_median_resale_price           0
days_to_first_resale           0
days_since_minting             0
transaction_frequency          0
price_volatility            3801
Background                     0
Fur                            0
Eyes                           0
Clothes                        0
Hat                            0
Mouth                          0
Earring                        0
month                          0
day_of_week                    0
linear_regression_trend        0
transaction_type               0
collection_name                0
dtype: int64
0

In [61]:
for col in cat_features:
    print(f"{col} unique values: ", X_train[col].unique())

Background unique values:  ['M1 Yellow' 'M1 Aquamarine' 'M1 Blue' 'M2 Gray' 'Army Green'
 'New Punk Blue' 'M1 Gray' 'M1 Purple' 'M2 Orange' 'M1 New Punk Blue'
 'Blue' 'M1 Army Green' 'Purple' 'Gray' 'M1 Orange' 'M2 New Punk Blue'
 'Yellow' 'Orange' 'Aquamarine' 'M2 Purple' 'M2 Blue' 'M2 Yellow'
 'M2 Aquamarine' 'M2 Army Green']
Fur unique values:  ['M1 Black' 'M1 Tan' 'M1 Dark Brown' 'M2 Black' 'M1 Brown' 'M1 Blue'
 'Dark Brown' 'Zombie' 'M1 Cheetah' 'M1 Cream' 'M2 Golden Brown' 'Robot'
 'Cream' 'Gray' 'Brown' 'Pink' 'M1 Red' 'M2 Robot' 'White' 'Cheetah'
 'Golden Brown' 'M1 Golden Brown' 'Black' 'M1 Zombie' 'Tan' 'M1 Robot'
 'Death Bot' 'M1 White' 'M1 Gray' 'M1 Dmt' 'M1 Pink' 'M2 Red' 'M2 White'
 'Blue' 'M2 Dark Brown' 'M2 Death Bot' 'M2 Brown' 'M1 Death Bot'
 'M2 Cream' 'Noise' 'M2 Tan' 'M2 Pink' 'M1 Noise' 'M2 Zombie' 'M2 Gray'
 'M2 Cheetah' 'Dmt' 'M1 Solid Gold' 'Red' 'M1 Trippy' 'M2 Blue' 'M2 Dmt'
 'Solid Gold' 'M2 Trippy' 'M2 Noise' 'Trippy' 'M2 Solid Gold']
Eyes unique values:  ['M1 Eyepatch' 'M1 Sleepy' 'M1 Sad' 'M2 Bloodshot' 'M1 Bored'
 'M1 Sunglasses' 'Bored' 'Coins' 'M1 Coins' 'M2 Crazy' 'M1 Zombie'
 'Wide Eyed' 'Bloodshot' 'M1 Closed' 'M1 3d' 'Crazy' 'Sleepy' 'M1 Cyborg'
 'M1 Angry' 'M2 Eyepatch' 'Closed' '3d' 'M1 Robot' 'Sunglasses' 'Sad'
 'M1 Bloodshot' 'Blindfold' 'M2 Sad' 'M1 Heart' 'M1 Blindfold' 'Angry'
 'M1 Wide Eyed' 'M2 Sleepy' 'X Eyes' 'M1 Hypnotized' 'M2 Robot'
 'M1 Holographic' 'M1 X Eyes' 'M2 Bored' 'M2 Scumbag' 'M2 Zombie'
 'Eyepatch' 'M1 Crazy' 'Heart' 'Robot' 'Hypnotized' 'M1 Laser Eyes'
 'Holographic' 'M2 Holographic' 'M2 Laser Eyes' 'Zombie' 'M1 Blue Beams'
 'Cyborg' 'M2 Wide Eyed' 'M2 Closed' 'M2 Sunglasses' 'M2 Cyborg'
 'M2 Angry' 'M1 Scumbag' 'Blue Beams' 'M2 Heart' 'Scumbag' 'Laser Eyes'
 'M2 Blindfold' 'M2 3d' 'M2 Hypnotized' 'M2 Coins' 'M2 X Eyes'
 'M2 Blue Beams']
Clothes unique values:  ['M1 Tanktop' 'M1 Toga' 'M1 Tuxedo Tee' 'M2 Wool Turtleneck'
 'M1 Sleeveless Logo T' 'Sailor Shirt' 'M1 Striped Tee' 'missing'
 'M2 Bone Tee' 'M1 Prison Jumpsuit' 'Toga' 'Service' 'M1 Smoking Jacket'
 'M1 Caveman Pelt' 'Hawaiian' 'M1 Wool Turtleneck' 'M1 Vietnam Jacket'
 'M1 Puffy Vest' 'M2 Sailor Shirt' 'Bone Tee' 'Kings Robe'
 'M1 Black Holes T' 'M1 Biker Vest' 'Lumberjack Shirt' 'M1 Bone Tee'
 'Lab Coat' 'M1 Sailor Shirt' 'M1 Bayc T Red' 'Leather Punk Jacket'
 'Bayc T Red' 'Prison Jumpsuit' 'Tweed Suit' 'Leather Jacket'
 'M1 Leather Jacket' 'M1 Bone Necklace' 'M2 Stunt Jacket' 'M1 Guayabera'
 'Black T' 'M1 Space Suit' 'M1 Black T' 'Prom Dress' 'M2 Striped Tee'
 'Caveman Pelt' 'M1 Navy Striped Tee' 'M1 Hip Hop' 'Tanktop'
 'M1 Stunt Jacket' 'Stunt Jacket' 'M1 Blue Dress' 'Sleeveless Logo T'
 'M1 Cowboy Shirt' 'Tuxedo Tee' 'M1 Work Vest' 'M1 Rainbow Suspenders'
 'M1 Lumberjack Shirt' 'M2 Sleeveless T' 'M1 Service' 'Guayabera'
 'Rainbow Suspenders' 'Wool Turtleneck' 'Bone Necklace' 'M2 Guayabera'
 'Smoking Jacket' 'M2 Bone Necklace' 'Navy Striped Tee' 'M1 Hawaiian'
 'M1 Leather Punk Jacket' 'Puffy Vest' 'Biker Vest' 'Work Vest'
 'Vietnam Jacket' 'M1 Pimp Coat' 'M1 Sleeveless T' 'Sleeveless T'
 'M2 Puffy Vest' 'M1 Tweed Suit' 'M1 Bayc T Black' 'Bandolier'
 'M2 Black T' 'M1 Lab Coat' 'Black Holes T' 'M2 Work Vest'
 'M2 Lumberjack Shirt' 'Hip Hop' 'Bayc T Black' 'M1 Bandolier'
 'M1 Kings Robe' 'M2 Prison Jumpsuit' 'M1 Tie Dye' 'M2 Hawaiian'
 'Blue Dress' 'M2 Leather Jacket' 'Cowboy Shirt' 'M2 Vietnam Jacket'
 'M2 Kings Robe' 'M2 Bandolier' 'M2 Tie Dye' 'Admirals Coat' 'M2 Hip Hop'
 'M2 Toga' 'Striped Tee' 'Space Suit' 'M1 Prom Dress'
 'M2 Rainbow Suspenders' 'M2 Caveman Pelt' 'M2 Bayc T Black'
 'M2 Navy Striped Tee' 'M2 Tuxedo Tee' 'Pimp Coat' 'M1 Admirals Coat'
 'M2 Prom Dress' 'M2 Smoking Jacket' 'M2 Black Suit' 'Tie Dye'
 'M2 Bayc T Red' 'M2 Service' 'M2 Tanktop' 'M1 Black Suit' 'M2 Biker Vest'
 'M2 Black Holes T' 'M2 Lab Coat' 'M2 Pimp Coat' 'M2 Leather Punk Jacket'
 'M2 Cowboy Shirt' 'M2 Sleeveless Logo T' 'M2 Admirals Coat'
 'M2 Tweed Suit' 'M2 Space Suit' 'Black Suit' 'M2 Blue Dress']
Hat unique values:  ['missing' 'M1 Halo' "M1 Fisherman's Hat" 'M1 Fez' 'M1 Short Mohawk'
 'M1 Police Motorcycle Helmet' "Trippy Captain's Hat"
 'M1 Sushi Chef Headband' 'M1 Beanie' 'M2 Cowboy Hat' 'M1 Bowler'
 'M1 S&m Hat' 'M1 Horns' 'M1 Cowboy Hat' "Girl's Hair Pink" 'M1 Safari'
 'Irish Boho' 'Horns' 'Bayc Hat Black' 'M1 Vietnam Era Helmet'
 'Commie Hat' 'M1 Faux Hawk' 'M1 Bunny Ears' 'Safari' 'Beanie' 'Army Hat'
 "Girl's Hair Short" "Sea Captain's Hat" 'M2 Bayc Hat Red'
 'M1 Ww2 Pilot Helm' "M2 Seaman's Hat" 'Bunny Ears' "M1 Girl's Hair Short"
 "M1 Seaman's Hat" 'M1 Bayc Flipped Brim' 'Sushi Chef Headband'
 'Bandana Blue' 'M1 Bandana Blue' 'M2 S&m Hat' "M1 Trippy Captain's Hat"
 'M1 Army Hat' 'M1 Prussian Helmet' "M1 Baby's Bonnet" 'M2 Bowler'
 'Faux Hawk' "Baby's Bonnet" 'M2 Prussian Helmet' 'Short Mohawk'
 'M2 Bayc Hat Black' 'Fez' "M1 Girl's Hair Pink" 'M1 Commie Hat'
 "Seaman's Hat" 'Police Motorcycle Helmet' "M1 Sea Captain's Hat"
 'Cowboy Hat' 'M1 Bayc Hat Black' 'M2 Police Motorcycle Helmet'
 'Stuntman Helmet' 'M1 Irish Boho' "Fisherman's Hat" 'M2 Spinner Hat'
 'M1 Party Hat 2' 'M2 Bunny Ears' 'M2 Fez' 'M2 Horns' 'M1 Laurel Wreath'
 "M1 King's Crown" 'M2 Army Hat' 'M1 Spinner Hat' 'Halo'
 'Bayc Flipped Brim' 'M1 Party Hat 1' 'Bowler' 'M2 Bandana Blue'
 'Laurel Wreath' 'M2 Bayc Flipped Brim' 'M2 Vietnam Era Helmet'
 'M2 Irish Boho' 'M2 Stuntman Helmet' "M2 Sea Captain's Hat"
 'M2 Short Mohawk' 'Vietnam Era Helmet' 'M2 Party Hat 1' 'Bayc Hat Red'
 "M2 Fisherman's Hat" "M2 Baby's Bonnet" 'M1 Stuntman Helmet'
 'M1 Bayc Hat Red' 'Ww2 Pilot Helm' 'Prussian Helmet'
 'M2 Sushi Chef Headband' 'S&m Hat' 'Party Hat 1' 'M2 Commie Hat'
 'M2 Beanie' 'M2 Safari' "M2 Girl's Hair Pink" 'M2 Faux Hawk'
 'Spinner Hat' 'Party Hat 2' "M2 Trippy Captain's Hat" 'M2 Ww2 Pilot Helm'
 "King's Crown" "M2 Girl's Hair Short" 'M2 Laurel Wreath' 'M2 Halo'
 "M2 King's Crown" 'M2 Party Hat 2']
Mouth unique values:  ['M1 Bored' 'M1 Bored Unshaven' 'M2 Bored Unshaven' 'M1 Phoneme Oh'
 'M1 Phoneme Vuh' 'M1 Grin' 'M1 Bored Unshaven Bubblegum' 'Phoneme  ooo'
 'Bored Unshaven Cigarette' 'M2 Dumbfounded' 'Rage' 'M1 Dumbfounded'
 'Bored' 'M1 Bored Cigarette' 'Bored Cigarette' 'Phoneme Wah'
 'M1 Small Grin' 'M1 Bored Dagger' 'M2 Rage' 'Bored Unshaven'
 'Dumbfounded' 'Small Grin' 'M1 Jovial' 'Jovial' 'Phoneme Oh' 'M1 Rage'
 'M1 Tongue Out' 'M2 Phoneme Oh' 'M1 Phoneme  Ooo'
 'M1 Bored Unshaven Cigarette' 'M2 Bored' 'M1 Bored Unshaven Party Horn'
 'M1 Bored Pizza' 'M1 Discomfort' 'Bored Unshaven Dagger'
 'M2 Bored Cigarette' 'M1 Grin Gold Grill' 'M2 Phoneme L'
 'M2 Bored Unshaven Bubblegum' 'Grin Diamond Grill' 'M1 Phoneme L'
 'M2 Bored Party Horn' 'Phoneme Vuh' 'M1 Bored Bubblegum' 'Grin'
 'Bored Party Horn' 'M1 Grin Multicolored' 'M1 Bored Unshaven Kazoo'
 'M2 Bored Unshaven Cigarette' 'Phoneme L' 'Bored Bubblegum'
 'M1 Bored Unshaven Pipe' 'M2 Grin' 'Bored Unshaven Cigar'
 'M2 Bored Unshaven Party Horn' 'Discomfort' 'M2 Grin Diamond Grill'
 'Tongue Out' 'M1 Grin Diamond Grill' 'Bored Cigar' 'M1 Phoneme Wah'
 'Bored Unshaven Pipe' 'Bored Unshaven Party horn' 'Bored Pipe'
 'M1 Bored Kazoo' 'M1 Bored Cigar' 'M2 Bored Unshaven Cigar' 'Bored Kazoo'
 'Grin Gold Grill' 'Bored Unshaven Bubblegum' 'Grin Multicolored'
 'M2 Small Grin' 'Bored Unshaven Kazoo' 'M1 Bored Unshaven Dagger'
 'M2 Tongue Out' 'M2 Phoneme Vuh' 'M2 Bored Unshaven Pipe'
 'M2 Bored Dagger' 'M1 Bored Pipe' 'M2 Discomfort'
 'M1 Bored Unshaven Cigar' 'Bored Dagger' 'Bored Pizza' 'M2 Jovial'
 'M2 Bored Kazoo' 'M2 Grin Multicolored' 'M1 Bored Party Horn'
 'M2 Bored Pipe' 'M2 Bored Unshaven Kazoo' 'M2 Phoneme Wah'
 'M1 Bored Unshaven Pizza' 'M2 Bored Pizza' 'Bored Unshaven Pizza'
 'M2 Bored Bubblegum' 'M2 Phoneme  Ooo' 'M2 Bored Cigar'
 'M2 Grin Gold Grill' 'M2 Bored Unshaven Pizza' 'M2 Bored Unshaven Dagger']
Earring unique values:  ['missing' 'Silver Hoop' 'Silver Stud' 'M2 Gold Hoop' 'M1 Silver Stud'
 'M1 Gold Stud' 'M1 Gold Hoop' 'M1 Silver Hoop' 'M2 Silver Stud'
 'Gold Stud' 'M2 Diamond Stud' 'M1 Diamond Stud' 'M1 Cross' 'Gold Hoop'
 'M2 Silver Hoop' 'M2 Gold Stud' 'Diamond Stud' 'Cross' 'M2 Cross']
month unique values:  ['August' 'January' 'March' 'June' 'May' 'April' 'November' 'February'
 'September' 'October' 'December' 'July']
day_of_week unique values:  ['Tuesday' 'Wednesday' 'Thursday' 'Sunday' 'Monday' 'Friday' 'Saturday']
linear_regression_trend unique values:  ['downward' 'upward' 'stable']
transaction_type unique values:  ['resale']
collection_name unique values:  ['MutantApeYachtClub' 'BoredApeYachtClub']

In [51]:
for col in cat_features:
    X_train[col].fillna("missing", inplace=True)
    X_val[col].fillna("missing", inplace=True)

In [54]:
nan_counts = X_train.isna().sum()
print(nan_counts[nan_counts > 0])

Clothes_rarity_score    10122
Hat_rarity_score        14038
Earring_rarity_score    42115
price_volatility         3801
Clothes                 10122
Hat                     14038
Earring                 42115
dtype: int64

In [55]:
print("NaN values in y_train:", y_train.isna().sum())
print("NaN values in y_val:", y_val.isna().sum())

NaN values in y_train: 0
NaN values in y_val: 0

In [56]:
# For categorical features in X_train and X_val
for col in cat_features:
    X_train[col].fillna("missing", inplace=True)
    X_val[col].fillna("missing", inplace=True)

# For numerical features in X_train and X_val
numerical_features = set(X_train.columns) - set(cat_features)
for col in numerical_features:
    median_value = X_train[col].median()
    X_train[col].fillna(median_value, inplace=True)
    X_val[col].fillna(median_value, inplace=True)

# If y_train or y_val has NaN values
y_train.dropna(inplace=True)
y_val.dropna(inplace=True)

TypeError: could not convert string to float: 'resale'

In [62]:
# Update the cat_features list
cat_features = ['Background', 'Fur', 'Eyes', 'Clothes', 'Hat', 'Mouth', 'Earring', 'month', 'day_of_week', 'transaction_type','linear_regression_trend','collection_name']

# Handle missing values for categorical features
for col in cat_features:
    X_train[col].fillna("missing", inplace=True)
    X_val[col].fillna("missing", inplace=True)

# Identify numerical features and handle missing values for them
numerical_features = set(X_train.columns) - set(cat_features)
for col in numerical_features:
    median_value = X_train[col].median()
    X_train[col].fillna(median_value, inplace=True)
    X_val[col].fillna(median_value, inplace=True)

# If y_train or y_val has NaN values
y_train.dropna(inplace=True)
y_val.dropna(inplace=True)

In [66]:
from catboost import CatBoostRegressor, Pool
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# 1. Handle missing values:

# Categorical features
cat_features = ['Background', 'Fur', 'Eyes', 'Clothes', 'Hat', 'Mouth', 'Earring', 'month', 'day_of_week', 'linear_regression_trend', 'transaction_type', 'collection_name']

for col in cat_features:
    X_train[col].fillna("missing", inplace=True)
    X_val[col].fillna("missing", inplace=True)

# Numerical features
numerical_features = set(X_train.columns) - set(cat_features)
for col in numerical_features:
    median_value = X_train[col].median()
    X_train[col].fillna(median_value, inplace=True)
    X_val[col].fillna(median_value, inplace=True)

# If y_train or y_val has NaN values
y_train.fillna(y_train.median(), inplace=True)
y_val.fillna(y_val.median(), inplace=True)

# 2. Convert data to CatBoost's Pool format
train_pool = Pool(data=X_train, label=y_train, cat_features=cat_features)
val_pool = Pool(data=X_val, label=y_val, cat_features=cat_features)

# 3. Initialize and train CatBoost Regressor

model = CatBoostRegressor(task_type="GPU", devices='0:1', verbose=0)

param_grid = {
    'learning_rate': [0.03, 0.1],
    'depth': [4, 6, 10],
    'l2_leaf_reg': [1, 5, 10],
    'iterations': [500]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train, y_train, cat_features=cat_features)

# Best parameters and model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# 4. Evaluate the model

y_pred = best_model.predict(X_val)
mse = mean_squared_error(y_val, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_val, y_pred)

print(f"Best Parameters: {best_params}")
print(f"Validation MSE: {mse}")
print(f"Validation RMSE: {rmse}")
print(f"Validation MAE: {mae}")

exception calling callback for <Future at 0x25d8fe594f0 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

In [67]:
# 1. Handle missing values:

# Categorical features
cat_features = ['Background', 'Fur', 'Eyes', 'Clothes', 'Hat', 'Mouth', 'Earring', 'month', 'day_of_week', 'linear_regression_trend', 'transaction_type', 'collection_name']

for col in cat_features:
    X_train[col].fillna("missing", inplace=True)
    X_val[col].fillna("missing", inplace=True)

# Numerical features
numerical_features = set(X_train.columns) - set(cat_features)
for col in numerical_features:
    median_value = X_train[col].median()
    X_train[col].fillna(median_value, inplace=True)
    X_val[col].fillna(median_value, inplace=True)

In [68]:
# If y_train or y_val has NaN values
y_train.fillna(y_train.median(), inplace=True)
y_val.fillna(y_val.median(), inplace=True)

# 2. Convert data to CatBoost's Pool format
train_pool = Pool(data=X_train, label=y_train, cat_features=cat_features)
val_pool = Pool(data=X_val, label=y_val, cat_features=cat_features)

In [70]:
# 3. Initialize and train CatBoost Regressor

# Initialize CatBoost Regressor
model = CatBoostRegressor(task_type="GPU", devices='0:1', verbose=0)

param_grid = {
    'learning_rate': [0.03, 0.1],
    'depth': [4, 6, 10],
    'l2_leaf_reg': [1, 5, 10],
    'iterations': [500]
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=2)
grid_search.fit(X_train, y_train, cat_features=cat_features)

# Rest of the code remains the same

exception calling callback for <Future at 0x25d8fe16550 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "C:\Users\USER\anaconda3\New folder\lib\site-packages\joblib\externals\loky\process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.